# Project: STL
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = FileName.o save.o
LINKOBJ  = FileName.o save.o
LIBS     = -L"C:/mingw64/lib" -L"C:/mingw64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/mingw64/include" -I"C:/mingw64/x86_64-w64-mingw32/include" -I"C:/mingw64/lib/gcc/x86_64-w64-mingw32/13.2.0/include"
CXXINCS  = -I"C:/mingw64/include" -I"C:/mingw64/x86_64-w64-mingw32/include" -I"C:/mingw64/lib/gcc/x86_64-w64-mingw32/13.2.0/include"
BIN      = STL.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

FileName.o: FileName.cpp
	$(CPP) -c FileName.cpp -o FileName.o $(CXXFLAGS)

save.o: save.cpp
	$(CPP) -c save.cpp -o save.o $(CXXFLAGS)
